language: node_js
node_js:
- node
- '8'
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: uAijoqnukwspPdEh6dxAwNU3nlqH0uokEMAgtg4HnH7v1l51drAKBQwcN+PLG0wkFd9n8A+qDvBO1SLnAze7E3usDZqLq7hAVQP8zvXOPhDNw3v6tptV0H97xw6uueuodJMRPgteZpyx4ZCEPpLQkX03riBxylohguoRA2cSiqItc5z/bQ9a79V1lECw7+rYu2WBZwyU/mh9hlqw4PxGlgYCH+XNjc8UReYnqbSM49W0V5ZRNYkgvvIkmneNlhkxg5hnbbQqeChtg8IcEMgzzEJfxe9pBYP+ul7hvJ/YgbL4udPN+ZbuzeympKXWz4VC40RgNGTuRpnfgw461gKKnAu19LYM5ArbkCvBCjPog7v/RM+k461TfNLmWf6J+oATltDJToO6e1txREDdXK4Gp1dgXasu8xpV+Xf19RUUKNtveTBTUJyPQAoUQ7gLArIwZPHheZKuBm4kKw4tJHnNIzKp/j1PsA+LMnZ5bvIF46jKFLQXyrv6gV3nV1G+HefCMibpR38xPrK3X0J4L7Mhg/8xokmXdixHtbeErGlUMXubL2IUA0922UZWopsOm0SyUQRPyUq8X56f7QkTkvDZLsblKSNAft7KuVKdU7o573Ir9d1ugGOK9Kkj/kXaBBzTTmEb7at0NcPQzICIy0CHZ4eo1i8GDw2tifNCRjHhcBo=
before_install:
- openssl aes-256-cbc -K $encrypted_ddd139318eaf_key -iv $encrypted_ddd139318eaf_iv
  -in credenciales.json.enc -out .privado/credenciales.json -d
