language: node_js
node_js:
- node
- '8'
sudo: false
deploy:
  provider: heroku
  api_key:
    secure: S7OuRj4fF6LQ9SNKFy3iGH0PcWHhvdEms6VVdPTwQY+lWBxvxDQpXmag56M8qH9lgID1WBdYGGUO6hV1MT0eJw2TNNxu+GDTMIE8Uv46HxbFrSemi4K4lZt+0zqFtBTXMSHqsq4vuo5H8GJ301MtXgkD4hRpecB1LLfZo+DaR95Vshg+doF7+XzANOBRG4tdFlJ6FW7EjsgSIs1VmP//mUVR1n6mxsjH7S3TA1+XSr32kn0P2KE0o8vus6qEYzvWPWQjRwAawsjF1/mp09OdzjgyUaVS4iQu7jDdcaKKYjyGK3YId0bsHHH9R5kimLoKukpgCn9N7+8RUcKYPp/StLJDexX3k5apkQsb55eifWeAqV1X8P4NKaTreWCKhs41ZcBnEREz7dzLAKgxfHB0UbXbobeDQmPaV4QOahhhYo25xBWq3vN15PYLCOvUei1QHUDcpgrjdrwiPfZT6KpZmkvRAvCfbET9i5zWTYQf0ArOeApBwa8iwoIYu6me8IqeUhSVZX8kwk44VPk+qM64mZVCZCeZKznfVRufMCNKGBpDNlfyNZ3Sr4UH6W9qQQhueScuDG8G9+bMFMlLIUXEoqbxRUKt5y/nIukkQAHEnW3SksJBqTHMw7fPobHQo+Y+c18SIxa2bmkVb+X5hCIBr7QzZlP27TxdhxJG7N2CKsw=
before_install:
- openssl aes-256-cbc -K $encrypted_ddd139318eaf_key -iv $encrypted_ddd139318eaf_iv
  -in credenciales.json.enc -out .privado/credenciales.json -d
